import fs from 'fs/promises';
import path from 'path';
import { getGenerateContentEndpoint } from './google-auth.js';

/** Narration script + per-segment scene prompts generated by Gemini. */
export interface StoryScript {
  narrationScript: string;
  scenes: { prompt: string }[];
}

function mimeTypeFor(imagePath: string): string {
  const ext = path.extname(imagePath).toLowerCase();
  if (ext === '.png') return 'image/png';
  if (ext === '.webp') return 'image/webp';
  return 'image/jpeg';
}

/**
 * Use Gemini to turn the user's pasted text (and reference images) into a
 * story: a narration script paced for the target length, plus one cinematic
 * scene prompt per 8-second Veo segment.
 */
export async function generateStory(opts: {
  storyText: string;
  imagePaths: string[];
  targetSeconds: number;
  segmentCount: number;
}): Promise<StoryScript> {
  const { storyText, imagePaths, targetSeconds, segmentCount } = opts;

  // Slightly under natural speech rate (~140 wpm) so the voiceover lands
  // inside the video; the mux time-scales any small overrun.
  const narrationWords = Math.floor((targetSeconds * 140) / 60);

  const imageNote =
    imagePaths.length > 0
      ? `\nThe user also attached ${imagePaths.length} reference image(s), shown above. ` +
        `Weave their subjects, settings, and mood into the story. Some video segments ` +
        `will be seeded directly from these images, so the corresponding scenes should ` +
        `feel continuous with them.`
      : '';

  const prompt = `You are creating a ${targetSeconds}-second vertical (9:16) social media video. Given the source text below, create:

1. A narration script of AT MOST ${narrationWords} words, paced to finish within \
${targetSeconds} seconds of natural speech — it must not run over. It should tell an \
informative, objective, and realistic story drawn from the source text, mimicking the style of a serious \
journalistic, educational, or historical documentary (e.g., PBS Frontline or BBC Horizon).
- Do NOT use generic intro/outro phrases, promotional hooks, or cinematic cliches (e.g., "Join us...", "In this video...", "Discover the secrets of...", "Let's explore...").
- Every single sentence must convey concrete information, key facts, specific dates, names of real people, places, or organizations, and actual statistics/numbers from the source text.
- Prioritize accuracy, objectivity, and informativeness over dramatic narrative or creative embellishment. Avoid vague summaries or simplifying details.

2. Exactly ${segmentCount} scene descriptions for 8-second video segments that flow as \
one continuous story. Each scene should visually illustrate part of the narration with \
cinematic motion. Describe camera movements, subjects, and visual style. The scenes must \
be purely visual with ambient sound only: no dialogue, speech, singing, or quoted text, \
and no on-screen text or labels. Keep imagery symbolic and family-friendly — avoid \
violence, weapons, suffering. While avoiding identifiable real or historical people in the prompts to pass \
video safety filters, describe stylized representations or visually abstract depictions of the events/concepts \
mentioned in the narration.${imageNote}

Source text:
${storyText.slice(0, 6000)}

Return ONLY valid JSON (no markdown fences) with this structure:
{
  "narrationScript": "The full narration text...",
  "scenes": [
    {"prompt": "Scene 1 description..."},
    {"prompt": "Scene 2 description..."}
  ]
}`;

  // Attach the reference images so the story actually reflects them
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const parts: any[] = [];
  for (const imagePath of imagePaths) {
    const buffer = await fs.readFile(imagePath);
    parts.push({
      inlineData: {
        mimeType: mimeTypeFor(imagePath),
        data: buffer.toString('base64'),
      },
    });
  }
  parts.push({ text: prompt });

  const model = process.env.GEMINI_TEXT_MODEL || 'gemini-3.5-flash';
  const { url, headers } = await getGenerateContentEndpoint(model);

  const response = await fetch(url, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      contents: [{ role: 'user', parts }],
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: 0.7,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Story generation failed: ${response.status} ${errorText.slice(0, 300)}`,
    );
  }

  const json = (await response.json()) as Record<string, any>;
  const responseParts: any[] =
    json?.candidates?.[0]?.content?.parts ?? [];

  // Join every text part — thinking models may split output — and strip
  // code fences Gemini sometimes adds despite instructions.
  let text = responseParts
    .map((p) => (typeof p?.text === 'string' ? p.text : ''))
    .join('')
    .trim();
  if (text.startsWith('```')) {
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
  }

  let script: StoryScript;
  try {
    script = JSON.parse(text) as StoryScript;
  } catch {
    console.error(`[story] Script JSON didn't decode: ${text.slice(0, 500)}`);
    throw new Error('Story generation returned invalid JSON');
  }

  if (!script.narrationScript || !Array.isArray(script.scenes) || script.scenes.length === 0) {
    throw new Error('Story generation returned an incomplete script');
  }

  console.log(
    `[story] Script generated (${script.scenes.length} scenes): ${script.narrationScript.slice(0, 100)}…`,
  );
  return script;
}

/** Deliberately safe fallback prompt for scenes rejected by the safety filter. */
export const SAFE_FALLBACK_SCENE =
  'A slow cinematic camera drift through an abstract, softly lit landscape of ' +
  'light, color, and gentle shapes, evoking a calm documentary mood. Ambient ' +
  'sound only. No people, no text, no dialogue.';
