import fs from 'fs/promises';
import path from 'path';
import { getGenerateContentEndpoint } from './google-auth.js';

/** Narration script + per-segment scene prompts generated by Gemini. */
export interface StoryScript {
  narrationScript: string;
  scenes: { prompt: string }[];
  caption: string;
}

function mimeTypeFor(imagePath: string): string {
  const ext = path.extname(imagePath).toLowerCase();
  if (ext === '.png') return 'image/png';
  if (ext === '.webp') return 'image/webp';
  return 'image/jpeg';
}

/**
 * Use Gemini to turn the user's pasted text (and reference images) into a
 * story: a narration script paced for the target length, plus one cinematic
 * scene prompt per 8-second Veo segment.
 */
export async function generateStory(opts: {
  storyText: string;
  imagePaths: string[];
  targetSeconds: number;
  segmentCount: number;
}): Promise<StoryScript> {
  const { storyText, imagePaths, targetSeconds, segmentCount } = opts;

  // Slightly under natural speech rate (~140 wpm) so the voiceover lands
  // inside the video; the mux time-scales any small overrun.
  const narrationWords = Math.floor((targetSeconds * 140) / 60);

  const imageNote =
    imagePaths.length > 0
      ? `\nThe user also attached ${imagePaths.length} reference image(s), shown above. ` +
        `Weave their subjects, settings, and mood into the story. Some video segments ` +
        `will be seeded directly from these images, so the corresponding scenes should ` +
        `feel continuous with them.`
      : '';

  const prompt = `You are creating a ${targetSeconds}-second vertical (9:16) social media video. Given the source text below, create:

1. A narration script of AT MOST ${narrationWords} words, paced to finish within \
${targetSeconds} seconds of natural speech — it must not run over. It should tell an \
informative, objective, and realistic story drawn from the source text, mimicking the style of a serious \
journalistic, educational, or historical documentary (e.g., PBS Frontline or BBC Horizon).
- Do NOT use generic intro/outro phrases, promotional hooks, or cinematic cliches (e.g., "Join us...", "In this video...", "Discover the secrets of...", "Let's explore...").
- Prefer to convey concrete information, key facts, specific dates, names of real people, places, or organizations, and actual statistics/numbers from the source text.
- Prioritize accuracy, objectivity, and informativeness over dramatic narrative or creative embellishment. Avoid vague summaries or simplifying details.
- CRITICAL: The narration will be read aloud by a text-to-speech model with strict content filters. \
The script MUST NOT mention: alcohol, alcoholism, drugs, drinking, drunkenness, guns, firearms, weapons, \
violence, aggression, injuries, death, crime, theft, sexual content, or any dangerous/harmful activities. \
If the source text covers these topics, either omit them entirely or reframe them in a safe, positive way \
(e.g., instead of 'alcoholism is common', say 'cultural customs may differ from what you expect').

2. Exactly ${segmentCount} scene descriptions for 8-second video segments that flow as \
one continuous story. Each scene should visually illustrate part of the narration with \
cinematic motion. Describe camera movements, subjects, and visual style. The scenes must \
be purely visual with ambient sound only: no dialogue, speech, singing, or quoted text, \
and no on-screen text or labels. Keep imagery symbolic and family-friendly — avoid \
violence, weapons, suffering. While avoiding identifiable real or historical people in the prompts to pass \
video safety filters, describe stylized representations or visually abstract depictions of the events/concepts \
mentioned in the narration.${imageNote}

3. A TikTok/social media caption (max 300 characters including hashtags). It should be attention-grabbing, \
informative, and include 3-5 relevant hashtags. Do NOT use generic hashtags like #fyp or #viral — use \
topic-specific ones drawn from the content.

Source text:
${storyText.slice(0, 6000)}

Return ONLY valid JSON (no markdown fences) with this structure:
{
  "narrationScript": "The full narration text...",
  "scenes": [
    {"prompt": "Scene 1 description..."},
    {"prompt": "Scene 2 description..."}
  ],
  "caption": "Your TikTok caption with #hashtags"
}`;

  // Attach the reference images so the story actually reflects them
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const parts: any[] = [];
  for (const imagePath of imagePaths) {
    const buffer = await fs.readFile(imagePath);
    parts.push({
      inlineData: {
        mimeType: mimeTypeFor(imagePath),
        data: buffer.toString('base64'),
      },
    });
  }
  parts.push({ text: prompt });

  const model = process.env.GEMINI_TEXT_MODEL || 'gemini-3.5-flash';
  const { url, headers } = await getGenerateContentEndpoint(model);

  const response = await fetch(url, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      contents: [{ role: 'user', parts }],
      generationConfig: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'OBJECT',
          properties: {
            narrationScript: { type: 'STRING' },
            scenes: {
              type: 'ARRAY',
              items: {
                type: 'OBJECT',
                properties: {
                  prompt: { type: 'STRING' },
                },
                required: ['prompt'],
              },
            },
            caption: { type: 'STRING' },
          },
          required: ['narrationScript', 'scenes', 'caption'],
        },
        temperature: 0.7,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Story generation failed: ${response.status} ${errorText.slice(0, 300)}`,
    );
  }

  const json = (await response.json()) as Record<string, any>;
  const finishReason = json?.candidates?.[0]?.finishReason;
  const responseParts: any[] =
    json?.candidates?.[0]?.content?.parts ?? [];

  // Log full response structure for debugging
  console.log(`[story] Response finishReason=${finishReason}, parts=${responseParts.length}`);
  for (let i = 0; i < responseParts.length; i++) {
    const p = responseParts[i];
    const hasText = typeof p?.text === 'string';
    const isThought = !!p?.thought;
    console.log(`[story]   part[${i}]: thought=${isThought}, hasText=${hasText}, len=${hasText ? p.text.length : 0}`);
  }

  // Check for safety block or empty response
  if (finishReason === 'SAFETY' || responseParts.length === 0) {
    throw new Error(`Story generation blocked (finishReason=${finishReason}). The source text may contain content that triggers safety filters.`);
  }

  // Filter out thought parts (thinking models return parts with `thought: true`
  // for internal reasoning) and join only the actual output text parts.
  const outputParts = responseParts.filter((p) => !p?.thought);
  let text = outputParts
    .map((p) => (typeof p?.text === 'string' ? p.text : ''))
    .join('')
    .trim();

  // If all parts were thought parts, fall back to joining ALL parts
  if (!text) {
    console.warn('[story] All parts were thought parts or empty — joining all parts as fallback');
    text = responseParts
      .map((p) => (typeof p?.text === 'string' ? p.text : ''))
      .join('')
      .trim();
  }

  // Strip code fences
  if (text.startsWith('```')) {
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
  }

  console.log(`[story] Combined text (${text.length} chars): ${text.slice(0, 300)}…`);

  // Try multiple strategies to extract valid JSON
  let script: StoryScript | null = null;

  // Strategy 1: Direct parse
  try {
    script = JSON.parse(text) as StoryScript;
  } catch {
    // Strategy 2: Extract the first JSON object from mixed content
    // (thinking text might have leaked despite filtering)
    const jsonMatch = text.match(/\{[\s\S]*"narrationScript"[\s\S]*"scenes"[\s\S]*\}/);
    if (jsonMatch) {
      try {
        script = JSON.parse(jsonMatch[0]) as StoryScript;
        console.log('[story] Extracted JSON via regex from mixed content');
      } catch {
        // Strategy 3: Try each non-thought part individually
        for (const p of outputParts) {
          if (typeof p?.text === 'string') {
            let partText = p.text.trim();
            if (partText.startsWith('```')) {
              partText = partText.replace(/```json/g, '').replace(/```/g, '').trim();
            }
            try {
              script = JSON.parse(partText) as StoryScript;
              console.log('[story] Parsed JSON from individual part');
              break;
            } catch {
              continue;
            }
          }
        }
      }
    }
  }

  if (!script) {
    console.error(`[story] All JSON parse strategies failed. Raw text: ${text.slice(0, 1000)}`);
    throw new Error('Story generation returned invalid JSON');
  }

  if (!script.narrationScript || !Array.isArray(script.scenes) || script.scenes.length === 0) {
    throw new Error('Story generation returned an incomplete script');
  }

  console.log(
    `[story] Script generated (${script.scenes.length} scenes): ${script.narrationScript.slice(0, 100)}…`,
  );
  return script;
}

/** Deliberately safe fallback prompt for scenes rejected by the safety filter. */
export const SAFE_FALLBACK_SCENE =
  'A slow cinematic camera drift through an abstract, softly lit landscape of ' +
  'light, color, and gentle shapes, evoking a calm documentary mood. Ambient ' +
  'sound only. No people, no text, no dialogue.';

// ---------------------------------------------------------------------------
// Character profile auto-generation
// ---------------------------------------------------------------------------

/**
 * Given the user's pasted source text, use Gemini to suggest a fitting narrator
 * character profile — a short persona description that the TTS model can adopt.
 */
export async function generateCharacterProfile(storyText: string): Promise<string> {
  const model = process.env.GEMINI_TEXT_MODEL || 'gemini-3.5-flash';
  const { url, headers } = await getGenerateContentEndpoint(model);

  const prompt = `You are a casting director. Based on the source text below, write a narrator persona description for a documentary voice-over.

Cover these aspects in a single flowing paragraph:
- Background and expertise that makes this narrator credible for the subject matter
- Vocal qualities (pitch, timbre, any accent coloring)
- Pacing (speaking speed, use of pauses)
- Emotional tone (e.g. gravitas, warmth, curiosity, dry wit)
- Delivery style (e.g. intimate, authoritative, conversational)

Example:
"A seasoned foreign correspondent who has spent decades covering conflict zones. Speaks with quiet authority — unhurried, deliberate pacing with meaningful pauses between revelations. A deep, resonant baritone with traces of a mid-Atlantic accent. Emotionally restrained but not cold; conveys weight through understatement rather than dramatic emphasis."

Write exactly one paragraph, 3-5 sentences, roughly 50-100 words. Be vivid and specific.

Source text (excerpt):
${storyText.slice(0, 3000)}

Respond with ONLY a JSON object: {"profile": "your persona description here"}`;

  const response = await fetch(url, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: 0.7,
        maxOutputTokens: 2048,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Character generation failed: ${response.status} ${errorText.slice(0, 200)}`);
  }

  /* eslint-disable @typescript-eslint/no-explicit-any */
  const json = (await response.json()) as Record<string, any>;
  const finishReason = json?.candidates?.[0]?.finishReason;
  const parts: any[] = json?.candidates?.[0]?.content?.parts ?? [];
  let text = parts
    .filter((p) => !p?.thought)
    .map((p) => (typeof p?.text === 'string' ? p.text : ''))
    .join('')
    .trim();

  if (!text) {
    throw new Error('Character generation returned empty response');
  }

  console.log(`[story] Character profile raw (${text.length} chars, finishReason=${finishReason}): ${text.slice(0, 200)}…`);

  // Strip code fences if present
  if (text.startsWith('```')) {
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
  }

  // Try full JSON parse first
  try {
    const parsed = JSON.parse(text) as { profile?: string };
    if (parsed.profile && typeof parsed.profile === 'string') {
      const profile = parsed.profile.trim();
      console.log(`[story] Character profile extracted (${profile.length} chars): ${profile.slice(0, 200)}…`);
      return profile;
    }
  } catch {
    console.warn('[story] Character profile JSON parse failed, attempting regex extraction');
  }

  // Fallback: extract the profile value via regex even from truncated JSON
  // e.g. {"profile": "An intrepid explorer who...   (cut off before closing quote/brace)
  const profileMatch = text.match(/"profile"\s*:\s*"((?:[^"\\]|\\.)*)("?)/s);
  if (profileMatch) {
    const extracted = profileMatch[1]
      .replace(/\\n/g, ' ')
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, '\\')
      .trim();
    if (extracted.length > 10) {
      console.log(`[story] Character profile regex-extracted (${extracted.length} chars): ${extracted.slice(0, 200)}…`);
      return extracted;
    }
  }

  // Last resort: strip all JSON artifacts and return whatever text remains
  const cleaned = text
    .replace(/^\s*\{\s*"profile"\s*:\s*"?/i, '')
    .replace(/"?\s*\}\s*$/, '')
    .replace(/\\n/g, ' ')
    .replace(/\\"/g, '"')
    .trim();

  console.log(`[story] Character profile last-resort cleanup (${cleaned.length} chars): ${cleaned.slice(0, 200)}…`);
  return cleaned || text;
}
