import fs from 'fs/promises';
import path from 'path';
import { getGenerateContentEndpoint } from './google-auth.js';

/** Narration script + per-segment scene prompts generated by Gemini. */
export interface StoryScript {
  narrationScript: string;
  scenes: { prompt: string }[];
  caption: string;
}

function mimeTypeFor(imagePath: string): string {
  const ext = path.extname(imagePath).toLowerCase();
  if (ext === '.png') return 'image/png';
  if (ext === '.webp') return 'image/webp';
  return 'image/jpeg';
}

/**
 * Use Gemini to turn the user's pasted text (and reference images) into a
 * story: a narration script paced for the target length, plus one cinematic
 * scene prompt per 8-second Veo segment.
 */
export async function generateStory(opts: {
  storyText: string;
  imagePaths: string[];
  targetSeconds: number;
  segmentCount: number;
}): Promise<StoryScript> {
  const { storyText, imagePaths, targetSeconds, segmentCount } = opts;

  // Slightly under natural speech rate (~140 wpm) so the voiceover lands
  // inside the video; the mux time-scales any small overrun.
  const narrationWords = Math.floor((targetSeconds * 140) / 60);

  const imageNote =
    imagePaths.length > 0
      ? `\nThe user also attached ${imagePaths.length} reference image(s), shown above. ` +
        `Weave their subjects, settings, and mood into the story. Some video segments ` +
        `will be seeded directly from these images, so the corresponding scenes should ` +
        `feel continuous with them.`
      : '';

  const prompt = `You are creating a ${targetSeconds}-second vertical (9:16) social media video. Given the source text below, create:

1. A narration script of AT MOST ${narrationWords} words, paced to finish within \
${targetSeconds} seconds of natural speech — it must not run over. It should tell an \
informative, objective, and realistic story drawn from the source text, mimicking the style of a serious \
journalistic, educational, or historical documentary (e.g., PBS Frontline or BBC Horizon).
- Do NOT use generic intro/outro phrases, promotional hooks, or cinematic cliches (e.g., "Join us...", "In this video...", "Discover the secrets of...", "Let's explore...").
- Prefer to convey concrete information, key facts, specific dates, names of real people, places, or organizations, and actual statistics/numbers from the source text.
- Prioritize accuracy, objectivity, and informativeness over dramatic narrative or creative embellishment. Avoid vague summaries or simplifying details.

2. Exactly ${segmentCount} scene descriptions for 8-second video segments that flow as \
one continuous story. Each scene should visually illustrate part of the narration with \
cinematic motion. Describe camera movements, subjects, and visual style. The scenes must \
be purely visual with ambient sound only: no dialogue, speech, singing, or quoted text, \
and no on-screen text or labels. Keep imagery symbolic and family-friendly — avoid \
violence, weapons, suffering. While avoiding identifiable real or historical people in the prompts to pass \
video safety filters, describe stylized representations or visually abstract depictions of the events/concepts \
mentioned in the narration.${imageNote}

3. A TikTok/social media caption (max 300 characters including hashtags). It should be attention-grabbing, \
informative, and include 3-5 relevant hashtags. Do NOT use generic hashtags like #fyp or #viral — use \
topic-specific ones drawn from the content.

Source text:
${storyText.slice(0, 6000)}

Return ONLY valid JSON (no markdown fences) with this structure:
{
  "narrationScript": "The full narration text...",
  "scenes": [
    {"prompt": "Scene 1 description..."},
    {"prompt": "Scene 2 description..."}
  ],
  "caption": "Your TikTok caption with #hashtags"
}`;

  // Attach the reference images so the story actually reflects them
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const parts: any[] = [];
  for (const imagePath of imagePaths) {
    const buffer = await fs.readFile(imagePath);
    parts.push({
      inlineData: {
        mimeType: mimeTypeFor(imagePath),
        data: buffer.toString('base64'),
      },
    });
  }
  parts.push({ text: prompt });

  const model = process.env.GEMINI_TEXT_MODEL || 'gemini-3.5-flash';
  const { url, headers } = await getGenerateContentEndpoint(model);

  const response = await fetch(url, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      contents: [{ role: 'user', parts }],
      generationConfig: {
        responseMimeType: 'application/json',
        temperature: 0.7,
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Story generation failed: ${response.status} ${errorText.slice(0, 300)}`,
    );
  }

  const json = (await response.json()) as Record<string, any>;
  const responseParts: any[] =
    json?.candidates?.[0]?.content?.parts ?? [];

  // Join every text part — thinking models may split output — and strip
  // code fences Gemini sometimes adds despite instructions.
  let text = responseParts
    .map((p) => (typeof p?.text === 'string' ? p.text : ''))
    .join('')
    .trim();
  if (text.startsWith('```')) {
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
  }

  let script: StoryScript;
  try {
    script = JSON.parse(text) as StoryScript;
  } catch {
    console.error(`[story] Script JSON didn't decode: ${text.slice(0, 500)}`);
    throw new Error('Story generation returned invalid JSON');
  }

  if (!script.narrationScript || !Array.isArray(script.scenes) || script.scenes.length === 0) {
    throw new Error('Story generation returned an incomplete script');
  }

  console.log(
    `[story] Script generated (${script.scenes.length} scenes): ${script.narrationScript.slice(0, 100)}…`,
  );
  return script;
}

/** Deliberately safe fallback prompt for scenes rejected by the safety filter. */
export const SAFE_FALLBACK_SCENE =
  'A slow cinematic camera drift through an abstract, softly lit landscape of ' +
  'light, color, and gentle shapes, evoking a calm documentary mood. Ambient ' +
  'sound only. No people, no text, no dialogue.';

// ---------------------------------------------------------------------------
// Character profile auto-generation
// ---------------------------------------------------------------------------

/**
 * Given the user's pasted source text, use Gemini to suggest a fitting narrator
 * character profile — a short persona description that the TTS model can adopt.
 */
export async function generateCharacterProfile(storyText: string): Promise<string> {
  const model = process.env.GEMINI_TEXT_MODEL || 'gemini-3.5-flash';
  const { url, headers } = await getGenerateContentEndpoint(model);

  const prompt = `You are a casting director writing voice-over direction for a documentary narrator. ` +
    `Based on the source text below, write a detailed narrator persona description.\n\n` +
    `Your description MUST include ALL of the following:\n` +
    `1. WHO the narrator is — their background, expertise, and perspective\n` +
    `2. VOCAL QUALITIES — pitch, timbre, accent hints (e.g. "mid-Atlantic", "warm Southern")\n` +
    `3. PACING AND RHYTHM — speaking speed, use of pauses, cadence\n` +
    `4. EMOTIONAL REGISTER — gravitas, warmth, curiosity, urgency, wry humor, etc.\n` +
    `5. DELIVERY STYLE — conversational vs. formal, intimate vs. authoritative\n\n` +
    `Example of the level of detail expected:\n` +
    `"A seasoned foreign correspondent who has spent decades covering conflict zones across the Middle East ` +
    `and Central Asia. Speaks with quiet authority and measured gravitas — unhurried, deliberate pacing with ` +
    `meaningful pauses between key revelations. A deep, resonant baritone with traces of a mid-Atlantic accent. ` +
    `Emotionally restrained but not cold; conveys weight and consequence through understatement rather than ` +
    `dramatic emphasis. Think of a veteran PBS Frontline narrator."\n\n` +
    `Write 3-5 sentences (150-400 words). Be vivid and specific.\n\n` +
    `Source text (first 3000 chars):\n${storyText.slice(0, 3000)}\n\n` +
    `Return ONLY the persona description — no quotes, no JSON, no preamble, no explanation, ` +
    `no word counts, no self-review, no meta-commentary. Just the persona itself.`;

  const response = await fetch(url, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: { temperature: 0.9, maxOutputTokens: 1024 },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Character generation failed: ${response.status} ${errorText.slice(0, 200)}`);
  }

  /* eslint-disable @typescript-eslint/no-explicit-any */
  const json = (await response.json()) as Record<string, any>;
  const finishReason = json?.candidates?.[0]?.finishReason;
  const parts: any[] = json?.candidates?.[0]?.content?.parts ?? [];
  const text = parts
    .map((p) => (typeof p?.text === 'string' ? p.text : ''))
    .join('')
    .trim();

  if (!text) {
    throw new Error('Character generation returned empty response');
  }

  console.log(`[story] Character profile raw (${text.length} chars, finishReason=${finishReason}): ${text.slice(0, 200)}…`);

  // Strip model self-review / meta-commentary that sometimes leaks through.
  // Look for lines that are clearly not part of the persona description.
  const metaPatterns = [
    /^let'?s\s+(review|check|verify|count)/i,
    /^(word|sentence|character)\s*(count|check)/i,
    /^\*\s*(sentences|words|word count)/i,
    /^(here is|here's|note:|caveat:|explanation:)/i,
    /^(i |my |this |the above)/i,
    /^\d+\s*(sentences?|words?)\s*[.:(]/i,
  ];

  const cleaned = text
    .split('\n')
    .filter((line) => {
      const trimmed = line.trim();
      if (!trimmed) return true; // keep blank lines between paragraphs
      return !metaPatterns.some((pat) => pat.test(trimmed));
    })
    .join('\n')
    .trim();

  console.log(`[story] Character profile cleaned (${cleaned.length} chars): ${cleaned.slice(0, 200)}…`);
  return cleaned || text; // fall back to raw text if cleaning removes everything
}
